// C declarations for the Rust ABI exported by moraine-duckdb (src/abi.rs,
// src/error.rs, src/runtime.rs, src/dumps/, src/staged.rs, src/inline.rs,
// src/arrow_ipc.rs).
//
// GENERATED by build.rs via cbindgen — do not edit. Change the Rust
// definitions and rebuild; every struct here matches its `#[repr(C)]`
// counterpart field for field, in declaration order.


#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
// The Arrow C Data Interface structs are defined by the embedder (DuckDB's
// Arrow headers); named here only.
typedef struct ArrowSchema ArrowSchema;
typedef struct ArrowArray ArrowArray;

// Mirrors `moraine_duckdb::error::codes` — pinned wire values.
enum {
	MORAINE_OK = 0,
	MORAINE_NOT_FOUND = 1,
	MORAINE_ALREADY_EXISTS = 2,
	MORAINE_CONSTRAINT = 3,
	MORAINE_COMMIT_CONFLICT = 4,
	MORAINE_CORRUPTION = 5,
	MORAINE_STORE = 6,
	MORAINE_INVALID_ARGUMENT = 7,
	MORAINE_INTERNAL = 8,
	MORAINE_INTERRUPTED = 9,
};


// An attached catalog: owns the tokio runtime created at `ATTACH` and
// the [`Catalog`] handle opened on it.
//
// Opaque to C — only ever seen as a `MoraineCatalogHandle*` obtained
// from [`moraine_attach`](crate::abi::moraine_attach) and released via
// [`moraine_detach`](crate::abi::moraine_detach).
//
// Every FFI entry point `block_on`s through `runtime`; nothing in
// `moraine` core ever blocks on itself.
typedef struct MoraineCatalogHandle MoraineCatalogHandle;

// A materialized snapshot view, held across the FFI boundary so
// listing calls need no further store I/O.
//
// Opaque to C — only ever seen as a `MoraineSnapshotHandle*` obtained
// from [`moraine_snapshot`](crate::abi::moraine_snapshot) and released
// via [`moraine_snapshot_free`](crate::abi::moraine_snapshot_free).
typedef struct MoraineSnapshotHandle MoraineSnapshotHandle;

// A staged-row transaction, opaque to C. Owns one [`StagedTransaction`]
// plus a borrowed pointer to the catalog handle it was opened on, used to
// `block_on` the async core calls in [`moraine_tx_begin`] and
// [`moraine_tx_commit`].
typedef struct MoraineTxHandle MoraineTxHandle;

// Mirrors the C `MoraineS3Config`: S3 credentials for an `s3://` store,
// sourced from a DuckDB secret. Null/empty fields fall back to the AWS_*
// environment; `use_ssl` is -1 unset, 0 false, 1 true.
typedef struct MoraineS3Config {
  // AWS access key id.
  const char *key_id;
  // AWS secret access key.
  const char *secret;
  // AWS region.
  const char *region;
  // AWS session token, for temporary credentials.
  const char *session_token;
  // Endpoint URL for S3-compatible stores (e.g. MinIO).
  const char *endpoint;
  // Addressing style: `"path"` or `"vhost"`.
  const char *url_style;
  // TLS toggle: -1 unset, 0 plain HTTP, 1 HTTPS.
  int32_t use_ssl;
} MoraineS3Config;

// The `(code, message)` pair carried across the FFI boundary.
//
// Caller-allocated and passed by pointer to every fallible `moraine_*`
// entry point; on failure the callee fills in both fields. `message` is
// null when there is nothing to free, and must be passed to
// [`moraine_error_free`](crate::abi::moraine_error_free) exactly once —
// the entry point never frees a previous message, so reuse without
// freeing in between leaks.
typedef struct MoraineError {
  // One of the [`codes`] constants.
  int32_t code;
  // A UTF-8, NUL-terminated, heap-allocated message, or null.
  char *message;
} MoraineError;

// A C-side cancellation probe polled while a cancellable call's core
// future is pending; returning `true` cancels the call. `None` disables
// the pull channel for that call. Mirrors `MoraineInterruptProbe` in
// `cpp/moraine_abi.h`.
typedef bool (*MoraineInterruptProbe)(void *probe_ctx);

// One schema, as returned by [`moraine_snapshot_schemas`].
typedef struct MoraineSchemaDesc {
  // The schema's id.
  uint64_t id;
  // The schema's name, owned — free via
  // [`moraine_snapshot_schemas_free`].
  char *name;
} MoraineSchemaDesc;

// One table, as returned by [`moraine_snapshot_tables_in`].
typedef struct MoraineTableDesc {
  // The table's id.
  uint64_t id;
  // The schema the table belongs to.
  uint64_t schema_id;
  // The table's name, owned — free via
  // [`moraine_snapshot_tables_in_free`].
  char *name;
} MoraineTableDesc;

// One column, as returned by [`moraine_snapshot_columns_of`].
typedef struct MoraineColumnDesc {
  // The column's field id.
  uint64_t id;
  // The column's name, owned — free via
  // [`moraine_snapshot_columns_of_free`].
  char *name;
  // The column's DuckLake type string, owned — free via
  // [`moraine_snapshot_columns_of_free`].
  char *sql_type;
  // Whether NULL values are allowed.
  bool nulls_allowed;
  // Whether this is a nested child column (a `STRUCT` field, `LIST`
  // element, or `MAP` key/value); `parent_column` is meaningful iff set.
  bool has_parent_column;
  // The parent column's field id when `has_parent_column`.
  uint64_t parent_column;
} MoraineColumnDesc;

// One view, as returned by [`moraine_snapshot_views_in`].
typedef struct MoraineViewDesc {
  // The view's id.
  uint64_t id;
  // The schema the view belongs to.
  uint64_t schema_id;
  // The view's name, owned — free via
  // [`moraine_snapshot_views_in_free`].
  char *name;
  // SQL dialect of the definition, owned — free via
  // [`moraine_snapshot_views_in_free`].
  char *dialect;
  // The view's defining SQL, owned — free via
  // [`moraine_snapshot_views_in_free`].
  char *sql;
} MoraineViewDesc;

// One live data file, as returned by [`moraine_snapshot_data_files_of`].
typedef struct MoraineDataFileDesc {
  // The file's id.
  uint64_t id;
  // Object-store path, owned — free via
  // [`moraine_snapshot_data_files_of_free`].
  char *path;
  // Whether `path` is relative to the table's location.
  bool path_is_relative;
  // Number of rows in the file.
  uint64_t record_count;
  // Whether `row_id_start` is present (absent when the file's rows
  // carry explicit per-row ids, e.g. compaction outputs).
  bool has_row_id_start;
  // First row id of the file's dense per-table row-id range, valid
  // iff `has_row_id_start`.
  uint64_t row_id_start;
  // Total file size in bytes.
  uint64_t file_size_bytes;
  // Footer size in bytes.
  uint64_t footer_size;
} MoraineDataFileDesc;

// One index, as returned by [`moraine_indexes`].
typedef struct MoraineIndexDesc {
  // The index's id.
  uint64_t index_id;
  // Whether the index enforces uniqueness.
  bool unique;
  // Whether a staged build is still in progress.
  bool building;
  // The index name, owned — free via [`moraine_indexes_free`].
  char *name;
} MoraineIndexDesc;

// A value passed to [`moraine_index_lookup`], tagged by kind. The shim
// fills the field matching `kind`; the ABI coerces it to the indexed
// column's canonical form.
typedef struct MoraineLookupValue {
  // `0`=IS NULL (a prefix predicate for [`moraine_index_nulls`]), `1`=i64,
  // `2`=u64, `3`=f64, `4`=bool, `5`=string, `6`=bytes.
  int32_t kind;
  // Valid iff `kind == 1`.
  int64_t i64_value;
  // Valid iff `kind == 2`.
  uint64_t u64_value;
  // Valid iff `kind == 3`.
  double f64_value;
  // Valid iff `kind == 4`.
  bool bool_value;
  // Valid iff `kind == 5`: a borrowed, NUL-terminated UTF-8 string.
  const char *str_value;
  // Valid iff `kind == 6`: a borrowed byte buffer of `bytes_len` bytes.
  const uint8_t *bytes_value;
  // Length of `bytes_value` when `kind == 6`.
  size_t bytes_len;
} MoraineLookupValue;

// One row an index lookup resolved, as returned by [`moraine_index_lookup`].
typedef struct MoraineRowLocation {
  // The row id the entry points at.
  uint64_t row_id;
  // The data file holding the row (valid when `is_inline` is false).
  uint64_t data_file_id;
  // Whether the row is inlined (or not resolvable to a dense-range file).
  bool is_inline;
} MoraineRowLocation;

// A byte buffer owned by Rust and freed via [`moraine_arrow_bytes_free`].
typedef struct MoraineArrowBytes {
  // Pointer to the buffer, or null on failure.
  uint8_t *data;
  // Length in bytes.
  size_t len;
  // Capacity, retained so the buffer can be reconstructed for freeing.
  size_t cap;
} MoraineArrowBytes;

// One `ducklake_schema` row, as returned by [`moraine_dump_schemas`].
typedef struct MoraineSchemaRow {
  // `schema_id`.
  uint64_t schema_id;
  // `schema_uuid`, owned.
  char *schema_uuid;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present (`false` for a live/current row).
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `schema_name`, owned.
  char *schema_name;
  // `path`, owned.
  char *path;
  // `path_is_relative`.
  bool path_is_relative;
} MoraineSchemaRow;

// One `ducklake_table` row, as returned by [`moraine_dump_tables`].
// `next_column_id` is moraine-internal field-id bookkeeping, not a
// DuckLake column, and is not carried here.
typedef struct MoraineTableRow {
  // `table_id`.
  uint64_t table_id;
  // `table_uuid`, owned.
  char *table_uuid;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `schema_id`.
  uint64_t schema_id;
  // `table_name`, owned.
  char *table_name;
  // `path`, owned.
  char *path;
  // `path_is_relative`.
  bool path_is_relative;
} MoraineTableRow;

// One `ducklake_view` row, as returned by [`moraine_dump_views`].
typedef struct MoraineViewRow {
  // `view_id`.
  uint64_t view_id;
  // `view_uuid`, owned.
  char *view_uuid;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `schema_id`.
  uint64_t schema_id;
  // `view_name`, owned.
  char *view_name;
  // `dialect`, owned.
  char *dialect;
  // `sql`, owned.
  char *sql;
  // `column_aliases`, owned, null if absent.
  char *column_aliases;
} MoraineViewRow;

// One `ducklake_column` row, as returned by [`moraine_dump_columns`].
// Column tags (`ducklake_column_tag`) are a separate table, not a
// column, and are not carried here.
typedef struct MoraineColumnRow {
  // `column_id`.
  uint64_t column_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `table_id`.
  uint64_t table_id;
  // `column_order`.
  uint64_t column_order;
  // `column_name`, owned.
  char *column_name;
  // `column_type`, owned.
  char *column_type;
  // `initial_default`, owned, null if absent.
  char *initial_default;
  // `default_value`, owned, null if absent.
  char *default_value;
  // `nulls_allowed`.
  bool nulls_allowed;
  // Whether `parent_column` is present.
  bool has_parent_column;
  // `parent_column`, valid iff `has_parent_column`.
  uint64_t parent_column;
  // `default_value_type`, owned, null if absent.
  char *default_value_type;
  // `default_value_dialect`, owned, null if absent.
  char *default_value_dialect;
} MoraineColumnRow;

// One `ducklake_data_file` row, as returned by
// [`moraine_dump_data_files`]. Per-file partition values
// (`ducklake_file_partition_value`) are a separate table and not
// carried here.
typedef struct MoraineDataFileRow {
  // `data_file_id`.
  uint64_t data_file_id;
  // `table_id`.
  uint64_t table_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // Whether `file_order` is present.
  bool has_file_order;
  // `file_order`, valid iff `has_file_order`.
  uint64_t file_order;
  // `path`, owned.
  char *path;
  // `path_is_relative`.
  bool path_is_relative;
  // `file_format`, owned.
  char *file_format;
  // `record_count`.
  uint64_t record_count;
  // `file_size_bytes`.
  uint64_t file_size_bytes;
  // `footer_size`.
  uint64_t footer_size;
  // Whether `row_id_start` is present (absent when the file's rows
  // carry explicit per-row ids, e.g. compaction outputs).
  bool has_row_id_start;
  // `row_id_start`, valid iff `has_row_id_start`.
  uint64_t row_id_start;
  // Whether `partition_id` is present.
  bool has_partition_id;
  // `partition_id`, valid iff `has_partition_id`.
  uint64_t partition_id;
  // `encryption_key`, owned, null if absent.
  char *encryption_key;
  // Whether `mapping_id` is present.
  bool has_mapping_id;
  // `mapping_id`, valid iff `has_mapping_id`.
  uint64_t mapping_id;
  // Whether `partial_max` is present.
  bool has_partial_max;
  // `partial_max`, valid iff `has_partial_max`.
  uint64_t partial_max;
} MoraineDataFileRow;

// One `ducklake_delete_file` row, as returned by
// [`moraine_dump_delete_files`].
typedef struct MoraineDeleteFileRow {
  // `delete_file_id`.
  uint64_t delete_file_id;
  // `table_id`.
  uint64_t table_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `data_file_id`.
  uint64_t data_file_id;
  // `path`, owned.
  char *path;
  // `path_is_relative`.
  bool path_is_relative;
  // `format`, owned.
  char *format;
  // `delete_count`.
  uint64_t delete_count;
  // `file_size_bytes`.
  uint64_t file_size_bytes;
  // `footer_size`.
  uint64_t footer_size;
  // `encryption_key`, owned, null if absent.
  char *encryption_key;
  // Whether `partial_max` is present.
  bool has_partial_max;
  // `partial_max`, valid iff `has_partial_max`.
  uint64_t partial_max;
} MoraineDeleteFileRow;

// One `ducklake_file_partition_value` row, as returned by
// [`moraine_dump_file_partition_values`] — flattened from the data-file
// record's embedded partition values.
typedef struct MoraineFilePartitionValueRow {
  // `data_file_id`.
  uint64_t data_file_id;
  // `table_id`.
  uint64_t table_id;
  // `partition_key_index`.
  uint64_t partition_key_index;
  // `partition_value`, owned.
  char *partition_value;
} MoraineFilePartitionValueRow;

// One `ducklake_files_scheduled_for_deletion` row, as returned by
// [`moraine_dump_scheduled_deletions`].
typedef struct MoraineScheduledDeletionRow {
  // `data_file_id`.
  uint64_t data_file_id;
  // `path`, owned.
  char *path;
  // `path_is_relative`.
  bool path_is_relative;
  // `schedule_start`, microseconds since epoch (UTC).
  int64_t schedule_start_micros;
} MoraineScheduledDeletionRow;

// One `ducklake_macro` row, as returned by [`moraine_dump_macros`].
typedef struct MoraineMacroRow {
  // `schema_id`.
  uint64_t schema_id;
  // `macro_id`.
  uint64_t macro_id;
  // `macro_name`, owned.
  char *macro_name;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
} MoraineMacroRow;

// One `ducklake_macro_impl` row, as returned by
// [`moraine_dump_macro_impls`].
typedef struct MoraineMacroImplRow {
  // `macro_id`.
  uint64_t macro_id;
  // `impl_id`.
  uint64_t impl_id;
  // `dialect`, owned.
  char *dialect;
  // `sql`, owned.
  char *sql;
  // `type`, owned.
  char *macro_type;
} MoraineMacroImplRow;

// One `ducklake_macro_parameters` row, as returned by
// [`moraine_dump_macro_parameters`].
typedef struct MoraineMacroParameterRow {
  // `macro_id`.
  uint64_t macro_id;
  // `impl_id`.
  uint64_t impl_id;
  // `column_id`: the parameter's 0-based position within its impl.
  uint64_t column_id;
  // `parameter_name`, owned.
  char *parameter_name;
  // `parameter_type`, owned.
  char *parameter_type;
  // `default_value`, owned, null if absent.
  char *default_value;
  // `default_value_type`, owned.
  char *default_value_type;
} MoraineMacroParameterRow;

// One `ducklake_column_mapping` row, as returned by
// [`moraine_dump_column_mappings`].
typedef struct MoraineColumnMappingRow {
  // `mapping_id`.
  uint64_t mapping_id;
  // `table_id`.
  uint64_t table_id;
  // `type`, owned.
  char *map_type;
} MoraineColumnMappingRow;

// One `ducklake_name_mapping` row, as returned by
// [`moraine_dump_name_mappings`].
typedef struct MoraineNameMappingRow {
  // `mapping_id`.
  uint64_t mapping_id;
  // `column_id`: the row's 0-based ordinal within its mapping.
  uint64_t column_id;
  // `source_name`, owned.
  char *source_name;
  // `target_field_id`.
  uint64_t target_field_id;
  // Whether `parent_column` is present.
  bool has_parent_column;
  // `parent_column`, valid iff `has_parent_column`.
  uint64_t parent_column;
  // `is_partition`.
  bool is_partition;
} MoraineNameMappingRow;

// One `ducklake_partition_info` row, as returned by
// [`moraine_dump_partition_info`]. Partition columns
// (`ducklake_partition_column`) are a separate table served by
// [`moraine_dump_partition_columns`].
typedef struct MorainePartitionInfoRow {
  // `partition_id`.
  uint64_t partition_id;
  // `table_id`.
  uint64_t table_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
} MorainePartitionInfoRow;

// One `ducklake_partition_column` row, as returned by
// [`moraine_dump_partition_columns`] — flattened from the partition
// record's embedded columns.
typedef struct MorainePartitionColumnRow {
  // `partition_id`.
  uint64_t partition_id;
  // `table_id`.
  uint64_t table_id;
  // `partition_key_index`.
  uint64_t partition_key_index;
  // `column_id`.
  uint64_t column_id;
  // `transform`, owned.
  char *transform;
} MorainePartitionColumnRow;

// One `ducklake_sort_info` row, as returned by
// [`moraine_dump_sort_info`]. Sort expressions
// (`ducklake_sort_expression`) are a separate table served by
// [`moraine_dump_sort_expressions`].
typedef struct MoraineSortInfoRow {
  // `sort_id`.
  uint64_t sort_id;
  // `table_id`.
  uint64_t table_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
} MoraineSortInfoRow;

// One `ducklake_sort_expression` row, as returned by
// [`moraine_dump_sort_expressions`] — flattened from the sort record's
// embedded expressions.
typedef struct MoraineSortExpressionRow {
  // `sort_id`.
  uint64_t sort_id;
  // `table_id`.
  uint64_t table_id;
  // `sort_key_index`.
  uint64_t sort_key_index;
  // `expression`, owned.
  char *expression;
  // `dialect`, owned.
  char *dialect;
  // `sort_direction`, owned.
  char *sort_direction;
  // `null_order`, owned.
  char *null_order;
} MoraineSortExpressionRow;

// One `ducklake_snapshot`/`ducklake_snapshot_changes` row (merged), as
// returned by [`moraine_dump_snapshots`]. `next_deletion_id` is
// moraine-internal gc-file counter bookkeeping, not a DuckLake column,
// and is not carried here.
typedef struct MoraineSnapshotRow {
  // `snapshot_id`.
  uint64_t snapshot_id;
  // `snapshot_time`, microseconds since the Unix epoch (UTC).
  int64_t snapshot_time_micros;
  // `schema_version`.
  uint64_t schema_version;
  // `next_catalog_id`.
  uint64_t next_catalog_id;
  // `next_file_id`.
  uint64_t next_file_id;
  // `changes_made`, owned.
  char *changes_made;
  // `author`, owned, null if absent.
  char *author;
  // `commit_message`, owned, null if absent.
  char *commit_message;
  // `commit_extra_info`, owned, null if absent.
  char *commit_extra_info;
} MoraineSnapshotRow;

// One `ducklake_schema_versions` row, as returned by
// [`moraine_dump_schema_versions`]: DuckLake's per-table schema-change
// history, flattened from the snapshot records it folds into (see
// `moraine::ffi_support::SchemaVersionRow`).
typedef struct MoraineSchemaVersionRow {
  // `begin_snapshot` — the snapshot the schema change landed in.
  uint64_t begin_snapshot;
  // `schema_version` — that snapshot's schema version.
  uint64_t schema_version;
  // `table_id` — the created-or-schema-altered table.
  uint64_t table_id;
} MoraineSchemaVersionRow;

// One `ducklake_table_stats` row, as returned by
// [`moraine_dump_table_stats`]. Unversioned — no lifecycle columns.
typedef struct MoraineTableStatsRow {
  // `table_id`.
  uint64_t table_id;
  // `record_count`.
  uint64_t record_count;
  // `next_row_id`.
  uint64_t next_row_id;
  // `file_size_bytes`.
  uint64_t file_size_bytes;
} MoraineTableStatsRow;

// One `ducklake_table_column_stats` row, as returned by
// [`moraine_dump_table_column_stats`]. Unversioned.
typedef struct MoraineTableColumnStatsRow {
  // `table_id`.
  uint64_t table_id;
  // `column_id`.
  uint64_t column_id;
  // Whether `contains_null` is present.
  bool has_contains_null;
  // `contains_null`, valid iff `has_contains_null`.
  bool contains_null;
  // Whether `contains_nan` is present.
  bool has_contains_nan;
  // `contains_nan`, valid iff `has_contains_nan`.
  bool contains_nan;
  // `min_value`, owned, null if absent.
  char *min_value;
  // `max_value`, owned, null if absent.
  char *max_value;
  // `extra_stats`, owned, null if absent.
  char *extra_stats;
} MoraineTableColumnStatsRow;

// One `ducklake_file_column_stats` row, as returned by
// [`moraine_dump_file_column_stats`]. Unversioned. Variant stats
// (`ducklake_file_variant_stats`) are a separate table and not carried
// here.
typedef struct MoraineFileColumnStatsRow {
  // `data_file_id`.
  uint64_t data_file_id;
  // `table_id`.
  uint64_t table_id;
  // `column_id`.
  uint64_t column_id;
  // `column_size_bytes`.
  uint64_t column_size_bytes;
  // `value_count`.
  uint64_t value_count;
  // `null_count`.
  uint64_t null_count;
  // `min_value`, owned, null if absent.
  char *min_value;
  // `max_value`, owned, null if absent.
  char *max_value;
  // Whether `contains_nan` is present.
  bool has_contains_nan;
  // `contains_nan`, valid iff `has_contains_nan`.
  bool contains_nan;
  // `extra_stats`, owned, null if absent.
  char *extra_stats;
} MoraineFileColumnStatsRow;

// One `ducklake_tag` row, as returned by [`moraine_dump_tags`] —
// flattened from the object's container record; ended entries included,
// lifecycle carried verbatim.
typedef struct MoraineTagRow {
  // `object_id`.
  uint64_t object_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `key`, owned.
  char *key;
  // `value`, owned.
  char *value;
} MoraineTagRow;

// One `ducklake_column_tag` row, as returned by
// [`moraine_dump_column_tags`] — flattened from the column's latest
// record (a version transition carries entries forward, so only the
// latest record's set is emitted).
typedef struct MoraineColumnTagRow {
  // `table_id`.
  uint64_t table_id;
  // `column_id`.
  uint64_t column_id;
  // `begin_snapshot`.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present.
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // `key`, owned.
  char *key;
  // `value`, owned.
  char *value;
} MoraineColumnTagRow;

// One inlined row, as returned by [`moraine_inline_scan`]: `chunk_index`
// names the owning chunk in the scan's parallel [`MoraineInlineChunk`]
// array, so the shim decodes each chunk once and reads the row at
// `offset_in_chunk`.
typedef struct MoraineInlineRow {
  // The row's dense id.
  uint64_t row_id;
  // The schema version the owning chunk was written under — selects the
  // `inline/schema` its body decodes against.
  uint64_t schema_version;
  // The commit snapshot that inserted this row.
  uint64_t begin_snapshot;
  // Whether `end_snapshot` is present (the row is live for `Table`
  // scans that return it, or tombstoned for the others).
  bool has_end_snapshot;
  // `end_snapshot`, valid iff `has_end_snapshot`.
  uint64_t end_snapshot;
  // The owning chunk: an index into the scan's chunk array.
  size_t chunk_index;
  // The row's offset within its chunk.
  uint64_t offset_in_chunk;
} MoraineInlineRow;

// One referenced chunk's full Arrow IPC record-batch body, owned —
// returned once per chunk however many rows reference it.
typedef struct MoraineInlineChunk {
  // The chunk's Arrow IPC record-batch body, owned.
  uint8_t *body;
  // `body`'s length in bytes.
  size_t body_len;
} MoraineInlineChunk;

// One `(schema_version, arrow_schema)` pair, as returned by
// [`moraine_inline_schemas`].
typedef struct MoraineInlineSchemaRow {
  // The schema's version.
  uint64_t schema_version;
  // The Arrow IPC schema message, owned, verbatim.
  uint8_t *arrow_schema;
  // `arrow_schema`'s length in bytes.
  size_t arrow_schema_len;
} MoraineInlineSchemaRow;

// One `(table_id, schema_version)` pair, as returned by
// [`moraine_inline_registered_tables`].
typedef struct MoraineInlineTableRow {
  // The table's id.
  uint64_t table_id;
  // The recorded schema version.
  uint64_t schema_version;
} MoraineInlineTableRow;

// One `ducklake_inlined_delete_<t>` row, as returned by
// [`moraine_inline_file_deletes`].
typedef struct MoraineInlineFileDeleteRow {
  // The targeted data file.
  uint64_t file_id;
  // The deleted row.
  uint64_t row_id;
  // The commit snapshot the delete takes effect at.
  uint64_t begin_snapshot;
} MoraineInlineFileDeleteRow;

// One value in a staged row. Mirrors [`Cell`] as a tagged struct across
// the C boundary; `str_value` is borrowed, valid only for the duration of
// the [`moraine_tx_stage`] call that reads it.
typedef struct MoraineCell {
  // `0` = NULL, `1` = u64, `2` = i64, `3` = bool, `4` = string.
  int32_t kind;
  // Valid iff `kind == 1`.
  uint64_t u64_value;
  // Valid iff `kind == 2`.
  int64_t i64_value;
  // Valid iff `kind == 3`.
  bool bool_value;
  // Valid iff `kind == 4`: a borrowed, NUL-terminated UTF-8 string.
  const char *str_value;
} MoraineCell;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Attaches a moraine catalog: creates the runtime this handle owns for
// its lifetime, opens (creating and initializing if empty) the catalog,
// and writes the resulting handle to `*out`.
//
// `path`'s scheme selects the store: a local filesystem directory
// (created if absent) by default, `memory://` for an in-memory store, or
// `s3://<bucket>[/<prefix>]` for S3. For an `s3://` path, `s3` supplies
// credentials (any field unset falls back to the AWS_* environment); it
// may be null to use the environment alone and is ignored otherwise.
//
// `encrypted` requests DuckLake data-file encryption. Creation-time
// only: it is recorded when a fresh store bootstraps and ignored on an
// already-initialized store, whose stored flag
// ([`moraine_catalog_encrypted`]) is authoritative.
//
// Returns [`codes::OK`] on success. On failure, `*out` is left
// unwritten and, if `err` is non-null, `*err` carries the code and a
// message.
//
// # Safety
//
// `path` must be a valid NUL-terminated C string. `s3`, if non-null,
// must point to a valid [`MoraineS3Config`] whose non-null fields are
// valid NUL-terminated C strings. `out` must be a valid, writable
// `*mut *mut MoraineCatalogHandle`. `err`, if non-null, must be a valid,
// writable [`MoraineError`]. All for the duration of this call.
int32_t moraine_attach(const char *path,
                       const struct MoraineS3Config *s3,
                       bool read_only,
                       bool encrypted,
                       uint64_t flush_interval_ms,
                       const char *cache_dir,
                       const char *data_path,
                       struct MoraineCatalogHandle **out,
                       struct MoraineError *err);

// Writes the lake's recorded data root — the stored global `data_path`
// option, set when the store was created — to `*out` as an owned C string,
// or null when none was recorded. Free a non-null result exactly once with
// [`moraine_string_free`]. The shim serves this back as DuckLake's
// `ducklake_metadata` `data_path` row, so a re-attach need not repeat it.
//
// Cancellable via `probe`/`probe_ctx`, exactly as
// [`moraine_snapshot`].
//
// # Safety
//
// `handle` must be a live handle from [`moraine_attach`]. `out` must be a
// valid, writable `*mut *mut c_char`. `probe`/`probe_ctx` follow the ABI
// cancellation contract. `err`, if non-null, must be writable. All for the
// duration of this call.
int32_t moraine_data_path(struct MoraineCatalogHandle *handle,
                          MoraineInterruptProbe probe,
                          void *probe_ctx,
                          char **out,
                          struct MoraineError *err);

// Frees a string previously written through [`moraine_data_path`]'s `out`.
// A null pointer is ignored.
//
// # Safety
//
// `ptr` must be a value written by [`moraine_data_path`] and not yet
// freed, or null.
void moraine_string_free(char *ptr);

// Whether the catalog encrypts its data files: the stored global
// `encrypted` option, fixed when the store was created. A store created
// before the flag existed reads as not encrypted.
//
// Cancellable via `probe`/`probe_ctx`, exactly as
// [`moraine_snapshot`].
//
// # Safety
//
// `handle` must be a live handle from [`moraine_attach`].
// `out_encrypted` must be a valid, writable `*mut bool`. `probe`, if
// non-null, must be safe to call with `probe_ctx` from any thread.
// `err`, if non-null, must be a valid, writable [`MoraineError`]. All
// for the duration of this call.
int32_t moraine_catalog_encrypted(struct MoraineCatalogHandle *handle,
                                  bool *out_encrypted,
                                  MoraineInterruptProbe probe,
                                  void *probe_ctx,
                                  struct MoraineError *err);

// Closes the catalog (flushing background work) and drops the runtime,
// consuming `handle`.
//
// Best-effort: a failure while closing the store is swallowed, since
// this `void` entry point has no error channel. A null `handle` is a
// no-op.
//
// # Safety
//
// `handle`, if non-null, must be a pointer previously returned by
// [`moraine_attach`] and not yet passed to `moraine_detach`.
void moraine_detach(struct MoraineCatalogHandle *handle);

// Materializes the catalog's current snapshot and writes the resulting
// handle to `*out`.
//
// Cancellable: races the core read against `probe` (polled
// immediately, then ~100 ms; a null `probe` disables polling). If a
// cancellation wins, returns [`codes::INTERRUPTED`] and `*out` is left
// unwritten.
//
// # Safety
//
// `handle` must be a pointer previously returned by [`moraine_attach`]
// and not yet detached. `out` must be a valid, writable
// `*mut *mut MoraineSnapshotHandle`. `probe`, if non-null, must be safe
// to call with `probe_ctx` from any thread. `err`, if non-null, must be
// a valid, writable [`MoraineError`]. All for the duration of this call.
int32_t moraine_snapshot(struct MoraineCatalogHandle *handle,
                         struct MoraineSnapshotHandle **out,
                         MoraineInterruptProbe probe,
                         void *probe_ctx,
                         struct MoraineError *err);

// Frees a snapshot handle previously returned by [`moraine_snapshot`].
// A null `snapshot` is a no-op.
//
// # Safety
//
// `snapshot`, if non-null, must be a pointer previously returned by
// [`moraine_snapshot`] and not yet freed.
void moraine_snapshot_free(struct MoraineSnapshotHandle *snapshot);

// Frees the message of an error previously populated by a `moraine_*`
// call. A null `message` is a no-op.
//
// # Safety
//
// `message`, if non-null, must be the exact pointer a `moraine_*` call
// wrote into [`MoraineError::message`], not yet freed.
void moraine_error_free(char *message);

// Lists the snapshot's live schemas into `*out_items`/`*out_len`.
//
// # Safety
//
// `snapshot` must be a pointer previously returned by
// [`moraine_snapshot`]. `out_items`/`out_len` must be valid, writable
// pointers. `err`, if non-null, must be a valid, writable
// [`MoraineError`]. All for the duration of this call.
int32_t moraine_snapshot_schemas(struct MoraineSnapshotHandle *snapshot,
                                 struct MoraineSchemaDesc **out_items,
                                 size_t *out_len,
                                 struct MoraineError *err);

// Frees an array returned by [`moraine_snapshot_schemas`].
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_snapshot_schemas`] call, not yet freed.
void moraine_snapshot_schemas_free(struct MoraineSchemaDesc *items, size_t len);

// Lists the live tables of schema `schema_id` into
// `*out_items`/`*out_len`. A schema with no live tables (or an unknown
// `schema_id`) yields an empty array, not an error.
//
// # Safety
//
// Same pointer contract as [`moraine_snapshot_schemas`].
int32_t moraine_snapshot_tables_in(struct MoraineSnapshotHandle *snapshot,
                                   uint64_t schema_id,
                                   struct MoraineTableDesc **out_items,
                                   size_t *out_len,
                                   struct MoraineError *err);

// Frees an array returned by [`moraine_snapshot_tables_in`].
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_snapshot_tables_in`] call, not yet freed.
void moraine_snapshot_tables_in_free(struct MoraineTableDesc *items, size_t len);

// Lists the live columns of table `table_id`, ordered by position, into
// `*out_items`/`*out_len`. An unknown `table_id` yields an empty array,
// not an error.
//
// # Safety
//
// Same pointer contract as [`moraine_snapshot_schemas`].
int32_t moraine_snapshot_columns_of(struct MoraineSnapshotHandle *snapshot,
                                    uint64_t table_id,
                                    struct MoraineColumnDesc **out_items,
                                    size_t *out_len,
                                    struct MoraineError *err);

// Frees an array returned by [`moraine_snapshot_columns_of`].
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_snapshot_columns_of`] call, not yet freed.
void moraine_snapshot_columns_of_free(struct MoraineColumnDesc *items, size_t len);

// Lists the live views of schema `schema_id` into
// `*out_items`/`*out_len`. A schema with no live views (or an unknown
// `schema_id`) yields an empty array, not an error.
//
// # Safety
//
// Same pointer contract as [`moraine_snapshot_schemas`].
int32_t moraine_snapshot_views_in(struct MoraineSnapshotHandle *snapshot,
                                  uint64_t schema_id,
                                  struct MoraineViewDesc **out_items,
                                  size_t *out_len,
                                  struct MoraineError *err);

// Frees an array returned by [`moraine_snapshot_views_in`].
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_snapshot_views_in`] call, not yet freed.
void moraine_snapshot_views_in_free(struct MoraineViewDesc *items, size_t len);

// Lists the live data files of table `table_id` into
// `*out_items`/`*out_len`. An unknown `table_id` yields an empty array,
// not an error.
//
// # Safety
//
// Same pointer contract as [`moraine_snapshot_schemas`].
int32_t moraine_snapshot_data_files_of(struct MoraineSnapshotHandle *snapshot,
                                       uint64_t table_id,
                                       struct MoraineDataFileDesc **out_items,
                                       size_t *out_len,
                                       struct MoraineError *err);

// Frees an array returned by [`moraine_snapshot_data_files_of`].
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_snapshot_data_files_of`] call, not yet freed.
void moraine_snapshot_data_files_of_free(struct MoraineDataFileDesc *items, size_t len);

// Creates an equality index, committing autonomously. Refuses a table that
// already holds data (SQL-path backfill is a follow-up).
//
// # Safety
//
// Every pointer must be valid per the ABI contract; `err`, if non-null,
// must be writable.
int32_t moraine_index_create(struct MoraineCatalogHandle *handle,
                             const char *schema_name,
                             const char *table_name,
                             const char *index_name,
                             const char *const *column_names,
                             size_t column_count,
                             const bool *column_descending,
                             const bool *column_nulls_first,
                             bool unique,
                             MoraineInterruptProbe probe,
                             void *probe_ctx,
                             struct MoraineError *err);

// Drops an equality index by name, committing autonomously.
//
// # Safety
//
// Every pointer must be valid per the ABI contract; `err`, if non-null,
// must be writable.
int32_t moraine_index_drop(struct MoraineCatalogHandle *handle,
                           const char *schema_name,
                           const char *table_name,
                           const char *index_name,
                           MoraineInterruptProbe probe,
                           void *probe_ctx,
                           struct MoraineError *err);

// Lists a table's live equality indexes.
//
// # Safety
//
// Every pointer must be valid per the ABI contract; `err`, if non-null,
// must be writable.
int32_t moraine_indexes(struct MoraineCatalogHandle *handle,
                        const char *schema_name,
                        const char *table_name,
                        struct MoraineIndexDesc **out_items,
                        size_t *out_len,
                        MoraineInterruptProbe probe,
                        void *probe_ctx,
                        struct MoraineError *err);

// Frees the array a [`moraine_indexes`] call returned.
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_indexes`] call, not yet freed.
void moraine_indexes_free(struct MoraineIndexDesc *items, size_t len);

// Resolves an equality lookup on a single-column index to the rows
// currently holding `lookup_value` — a [`MoraineLookupValue`] the ABI
// coerces to the indexed column's type. v1 resolves a single value.
//
// # Safety
//
// Every pointer must be valid per the ABI contract; `err`, if non-null,
// must be writable.
int32_t moraine_index_lookup(struct MoraineCatalogHandle *handle,
                             const char *schema_name,
                             const char *table_name,
                             const char *index_name,
                             const struct MoraineLookupValue *lookup_value,
                             struct MoraineRowLocation **out_items,
                             size_t *out_len,
                             MoraineInterruptProbe probe,
                             void *probe_ctx,
                             struct MoraineError *err);

// Frees the array a [`moraine_index_lookup`] call returned.
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_index_lookup`] call, not yet freed.
void moraine_index_lookup_free(struct MoraineRowLocation *items, size_t len);

// Resolves a comparison query on a single-column index to the rows whose
// value falls between the bounds. A null bound pointer is unbounded (an open
// side); a present bound is `Included` when its `*_inclusive` flag is set,
// `Excluded` otherwise. Results come back in the index's stored order.
//
// # Safety
//
// Every non-null pointer must be valid per the ABI contract; `err`, if
// non-null, must be writable.
int32_t moraine_index_range(struct MoraineCatalogHandle *handle,
                            const char *schema_name,
                            const char *table_name,
                            const char *index_name,
                            const struct MoraineLookupValue *lower_value,
                            bool lower_inclusive,
                            const struct MoraineLookupValue *upper_value,
                            bool upper_inclusive,
                            bool reverse,
                            struct MoraineRowLocation **out_items,
                            size_t *out_len,
                            MoraineInterruptProbe probe,
                            void *probe_ctx,
                            struct MoraineError *err);

// Frees the array a [`moraine_index_range`] call returned.
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a matching
// [`moraine_index_range`] call, not yet freed.
void moraine_index_range_free(struct MoraineRowLocation *items, size_t len);

// Resolves an `IS NULL` query on an index to the matching rows. `prefix` is a
// leading run of predicates over the index's columns: a `MoraineLookupValue`
// of `kind == 0` is `IS NULL` for that column, any other kind is `= value`.
// At least one must be `IS NULL`; a bare non-leading `IS NULL` is not
// expressible (the prefix covers the leading columns).
//
// # Safety
//
// Every non-null pointer must be valid per the ABI contract; `prefix` points
// to `prefix_len` values; `err`, if non-null, must be writable.
int32_t moraine_index_nulls(struct MoraineCatalogHandle *handle,
                            const char *schema_name,
                            const char *table_name,
                            const char *index_name,
                            const struct MoraineLookupValue *prefix,
                            size_t prefix_len,
                            bool reverse,
                            struct MoraineRowLocation **out_items,
                            size_t *out_len,
                            MoraineInterruptProbe probe,
                            void *probe_ctx,
                            struct MoraineError *err);

// Frees the array a [`moraine_index_nulls`] call returned.
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a matching
// [`moraine_index_nulls`] call, not yet freed.
void moraine_index_nulls_free(struct MoraineRowLocation *items, size_t len);

// Frees a buffer returned by an encode call.
//
// # Safety
// `bytes` must be a value returned by a `moraine_arrow_encode_*` call and
// not previously freed.
void moraine_arrow_bytes_free(struct MoraineArrowBytes bytes);

// Serializes just the Arrow schema (an IPC stream with the schema and no
// batches), stored once per inline schema version so an empty scan can
// reconstruct the column layout.
//
// # Safety
// `schema` is an exported `ArrowSchema` consumed by this call; `out`/`err`
// are valid writable pointers.
int32_t moraine_arrow_encode_schema(ArrowSchema *schema,
                                    struct MoraineArrowBytes *out,
                                    struct MoraineError *err);

// Serializes one inlined chunk to a record-batch **body** only — the IPC
// record-batch message and its buffers, without a schema message. The
// schema is stored once per version by [`moraine_arrow_encode_schema`] and
// supplied back at decode by [`moraine_arrow_decode_body`], so the WAL
// append for a tiny commit never re-serializes the schema. The layout is a
// little-endian `u32` message length, the record-batch flatbuffer message,
// then the arrow data buffers.
//
// Dictionary-encoded columns are rejected: the body carries no dictionary
// messages. Inlined user columns are not dictionary-encoded in practice.
//
// # Safety
// `schema`/`array` are exported structs consumed by this call; `out`/`err`
// are valid writable pointers.
int32_t moraine_arrow_encode_chunk(ArrowSchema *schema,
                                   ArrowArray *array,
                                   struct MoraineArrowBytes *out,
                                   struct MoraineError *err);

// Decodes a chunk body from [`moraine_arrow_encode_chunk`] against the
// schema stored for its version (`schema_ipc` is that version's schema-only
// IPC stream). Produces exported C Data Interface structs the shim feeds to
// DuckDB's Arrow import; the caller (via DuckDB's importer) owns releasing
// them.
//
// # Safety
// `schema_ipc`/`body` point to `schema_ipc_len`/`body_len` readable bytes;
// `out_schema`/`out_array` are writable slots the caller releases; `err` is
// writable.
int32_t moraine_arrow_decode_body(const uint8_t *schema_ipc,
                                  size_t schema_ipc_len,
                                  const uint8_t *body,
                                  size_t body_len,
                                  ArrowSchema *out_schema,
                                  ArrowArray *out_array,
                                  struct MoraineError *err);

// Decodes a self-contained IPC stream (from [`moraine_arrow_encode_chunk`],
// or a schema-only stream from [`moraine_arrow_encode_schema`], which
// yields an empty batch) into exported C Data Interface structs the shim
// feeds to DuckDB's Arrow import.
//
// # Safety
// `body` points to `body_len` readable bytes; `out_schema`/`out_array` are
// writable slots the caller (DuckDB) will release; `err` is writable.
int32_t moraine_arrow_decode_stream(const uint8_t *body,
                                    size_t body_len,
                                    ArrowSchema *out_schema,
                                    ArrowArray *out_array,
                                    struct MoraineError *err);

// Dumps every `ducklake_schema` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_schemas(struct MoraineCatalogHandle *handle,
                             struct MoraineSchemaRow **out_items,
                             size_t *out_len,
                             MoraineInterruptProbe probe,
                             void *probe_ctx,
                             struct MoraineError *err);

// Frees the array returned by [`moraine_dump_schemas`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_schemas`] call
// wrote, not yet freed.
void moraine_dump_schemas_free(struct MoraineSchemaRow *items, size_t len);

// Dumps every `ducklake_table` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_tables(struct MoraineCatalogHandle *handle,
                            struct MoraineTableRow **out_items,
                            size_t *out_len,
                            MoraineInterruptProbe probe,
                            void *probe_ctx,
                            struct MoraineError *err);

// Frees the array returned by [`moraine_dump_tables`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_tables`] call
// wrote, not yet freed.
void moraine_dump_tables_free(struct MoraineTableRow *items, size_t len);

// Dumps every `ducklake_view` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_views(struct MoraineCatalogHandle *handle,
                           struct MoraineViewRow **out_items,
                           size_t *out_len,
                           MoraineInterruptProbe probe,
                           void *probe_ctx,
                           struct MoraineError *err);

// Frees the array returned by [`moraine_dump_views`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_views`] call
// wrote, not yet freed.
void moraine_dump_views_free(struct MoraineViewRow *items, size_t len);

// Dumps every `ducklake_column` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_columns(struct MoraineCatalogHandle *handle,
                             struct MoraineColumnRow **out_items,
                             size_t *out_len,
                             MoraineInterruptProbe probe,
                             void *probe_ctx,
                             struct MoraineError *err);

// Frees the array returned by [`moraine_dump_columns`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_columns`] call
// wrote, not yet freed.
void moraine_dump_columns_free(struct MoraineColumnRow *items, size_t len);

// Dumps every `ducklake_data_file` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_data_files(struct MoraineCatalogHandle *handle,
                                struct MoraineDataFileRow **out_items,
                                size_t *out_len,
                                MoraineInterruptProbe probe,
                                void *probe_ctx,
                                struct MoraineError *err);

// Frees the array returned by [`moraine_dump_data_files`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_data_files`] call
// wrote, not yet freed.
void moraine_dump_data_files_free(struct MoraineDataFileRow *items, size_t len);

// Dumps every `ducklake_delete_file` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_delete_files(struct MoraineCatalogHandle *handle,
                                  struct MoraineDeleteFileRow **out_items,
                                  size_t *out_len,
                                  MoraineInterruptProbe probe,
                                  void *probe_ctx,
                                  struct MoraineError *err);

// Frees the array returned by [`moraine_dump_delete_files`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_delete_files`] call
// wrote, not yet freed.
void moraine_dump_delete_files_free(struct MoraineDeleteFileRow *items, size_t len);

// Dumps every `ducklake_file_partition_value` row — one per embedded
// partition value of every data-file record, current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_file_partition_values(struct MoraineCatalogHandle *handle,
                                           struct MoraineFilePartitionValueRow **out_items,
                                           size_t *out_len,
                                           MoraineInterruptProbe probe,
                                           void *probe_ctx,
                                           struct MoraineError *err);

// Frees the array returned by [`moraine_dump_file_partition_values`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_file_partition_values`] call
// wrote, not yet freed.
void moraine_dump_file_partition_values_free(struct MoraineFilePartitionValueRow *items,
                                             size_t len);

// Dumps every `ducklake_files_scheduled_for_deletion` row into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_scheduled_deletions(struct MoraineCatalogHandle *handle,
                                         struct MoraineScheduledDeletionRow **out_items,
                                         size_t *out_len,
                                         MoraineInterruptProbe probe,
                                         void *probe_ctx,
                                         struct MoraineError *err);

// Frees the array returned by [`moraine_dump_scheduled_deletions`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_scheduled_deletions`] call
// wrote, not yet freed.
void moraine_dump_scheduled_deletions_free(struct MoraineScheduledDeletionRow *items, size_t len);

// Dumps every `ducklake_macro` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_macros(struct MoraineCatalogHandle *handle,
                            struct MoraineMacroRow **out_items,
                            size_t *out_len,
                            MoraineInterruptProbe probe,
                            void *probe_ctx,
                            struct MoraineError *err);

// Frees the array returned by [`moraine_dump_macros`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_macros`] call
// wrote, not yet freed.
void moraine_dump_macros_free(struct MoraineMacroRow *items, size_t len);

// Dumps every `ducklake_macro_impl` row — flattened from the embedded
// implementations of every macro record, history included, ordered by
// `(macro_id, impl_id)`. DuckLake's macro reconstruction consumes rows
// in served order.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_macro_impls(struct MoraineCatalogHandle *handle,
                                 struct MoraineMacroImplRow **out_items,
                                 size_t *out_len,
                                 MoraineInterruptProbe probe,
                                 void *probe_ctx,
                                 struct MoraineError *err);

// Frees the array returned by [`moraine_dump_macro_impls`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_macro_impls`] call
// wrote, not yet freed.
void moraine_dump_macro_impls_free(struct MoraineMacroImplRow *items, size_t len);

// Dumps every `ducklake_macro_parameters` row — flattened from the
// embedded parameters of every implementation, history included, ordered
// by `(macro_id, impl_id, column_id)`. DuckLake's macro reconstruction
// consumes rows in served order.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_macro_parameters(struct MoraineCatalogHandle *handle,
                                      struct MoraineMacroParameterRow **out_items,
                                      size_t *out_len,
                                      MoraineInterruptProbe probe,
                                      void *probe_ctx,
                                      struct MoraineError *err);

// Frees the array returned by [`moraine_dump_macro_parameters`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_macro_parameters`] call
// wrote, not yet freed.
void moraine_dump_macro_parameters_free(struct MoraineMacroParameterRow *items, size_t len);

// Dumps every `ducklake_column_mapping` row into
// `*out_items`/`*out_len`. Mappings are unversioned create-only records,
// so this is exactly the live rows.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_column_mappings(struct MoraineCatalogHandle *handle,
                                     struct MoraineColumnMappingRow **out_items,
                                     size_t *out_len,
                                     MoraineInterruptProbe probe,
                                     void *probe_ctx,
                                     struct MoraineError *err);

// Frees the array returned by [`moraine_dump_column_mappings`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_column_mappings`] call
// wrote, not yet freed.
void moraine_dump_column_mappings_free(struct MoraineColumnMappingRow *items, size_t len);

// Dumps every `ducklake_name_mapping` row — flattened from the embedded
// rows of every mapping record, ordered by `(mapping_id, column_id)` —
// into `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_name_mappings(struct MoraineCatalogHandle *handle,
                                   struct MoraineNameMappingRow **out_items,
                                   size_t *out_len,
                                   MoraineInterruptProbe probe,
                                   void *probe_ctx,
                                   struct MoraineError *err);

// Frees the array returned by [`moraine_dump_name_mappings`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_name_mappings`] call
// wrote, not yet freed.
void moraine_dump_name_mappings_free(struct MoraineNameMappingRow *items, size_t len);

// Dumps every `ducklake_partition_info` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_partition_info(struct MoraineCatalogHandle *handle,
                                    struct MorainePartitionInfoRow **out_items,
                                    size_t *out_len,
                                    MoraineInterruptProbe probe,
                                    void *probe_ctx,
                                    struct MoraineError *err);

// Frees the array returned by [`moraine_dump_partition_info`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_partition_info`] call
// wrote, not yet freed.
void moraine_dump_partition_info_free(struct MorainePartitionInfoRow *items, size_t len);

// Dumps every `ducklake_partition_column` row — one per embedded column
// of every partition record, current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_partition_columns(struct MoraineCatalogHandle *handle,
                                       struct MorainePartitionColumnRow **out_items,
                                       size_t *out_len,
                                       MoraineInterruptProbe probe,
                                       void *probe_ctx,
                                       struct MoraineError *err);

// Frees the array returned by [`moraine_dump_partition_columns`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_partition_columns`] call
// wrote, not yet freed.
void moraine_dump_partition_columns_free(struct MorainePartitionColumnRow *items, size_t len);

// Dumps every `ducklake_sort_info` row — current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_sort_info(struct MoraineCatalogHandle *handle,
                               struct MoraineSortInfoRow **out_items,
                               size_t *out_len,
                               MoraineInterruptProbe probe,
                               void *probe_ctx,
                               struct MoraineError *err);

// Frees the array returned by [`moraine_dump_sort_info`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_sort_info`] call
// wrote, not yet freed.
void moraine_dump_sort_info_free(struct MoraineSortInfoRow *items, size_t len);

// Dumps every `ducklake_sort_expression` row — one per embedded
// expression of every sort record, current and history — into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_sort_expressions(struct MoraineCatalogHandle *handle,
                                      struct MoraineSortExpressionRow **out_items,
                                      size_t *out_len,
                                      MoraineInterruptProbe probe,
                                      void *probe_ctx,
                                      struct MoraineError *err);

// Frees the array returned by [`moraine_dump_sort_expressions`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_sort_expressions`] call
// wrote, not yet freed.
void moraine_dump_sort_expressions_free(struct MoraineSortExpressionRow *items, size_t len);

// Dumps every `ducklake_snapshot` row into `*out_items`/`*out_len`.
// Snapshots carry no begin/end lifecycle of their own — this is the
// full committed history, not a current/history split.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_snapshots(struct MoraineCatalogHandle *handle,
                               struct MoraineSnapshotRow **out_items,
                               size_t *out_len,
                               MoraineInterruptProbe probe,
                               void *probe_ctx,
                               struct MoraineError *err);

// Frees the array returned by [`moraine_dump_snapshots`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_snapshots`] call
// wrote, not yet freed.
void moraine_dump_snapshots_free(struct MoraineSnapshotRow *items, size_t len);

// Dumps every `ducklake_schema_versions` row into
// `*out_items`/`*out_len`, in snapshot order.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_schema_versions(struct MoraineCatalogHandle *handle,
                                     struct MoraineSchemaVersionRow **out_items,
                                     size_t *out_len,
                                     MoraineInterruptProbe probe,
                                     void *probe_ctx,
                                     struct MoraineError *err);

// Frees the array returned by [`moraine_dump_schema_versions`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_schema_versions`] call
// wrote, not yet freed.
void moraine_dump_schema_versions_free(struct MoraineSchemaVersionRow *items, size_t len);

// Dumps every `ducklake_table_stats` row into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_table_stats(struct MoraineCatalogHandle *handle,
                                 struct MoraineTableStatsRow **out_items,
                                 size_t *out_len,
                                 MoraineInterruptProbe probe,
                                 void *probe_ctx,
                                 struct MoraineError *err);

// Frees the array returned by [`moraine_dump_table_stats`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_table_stats`] call
// wrote, not yet freed.
void moraine_dump_table_stats_free(struct MoraineTableStatsRow *items, size_t len);

// Dumps every `ducklake_table_column_stats` row into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_table_column_stats(struct MoraineCatalogHandle *handle,
                                        struct MoraineTableColumnStatsRow **out_items,
                                        size_t *out_len,
                                        MoraineInterruptProbe probe,
                                        void *probe_ctx,
                                        struct MoraineError *err);

// Frees the array returned by [`moraine_dump_table_column_stats`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_table_column_stats`] call
// wrote, not yet freed.
void moraine_dump_table_column_stats_free(struct MoraineTableColumnStatsRow *items, size_t len);

// Dumps every `ducklake_file_column_stats` row into
// `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_file_column_stats(struct MoraineCatalogHandle *handle,
                                       struct MoraineFileColumnStatsRow **out_items,
                                       size_t *out_len,
                                       MoraineInterruptProbe probe,
                                       void *probe_ctx,
                                       struct MoraineError *err);

// Frees the array returned by [`moraine_dump_file_column_stats`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_file_column_stats`] call
// wrote, not yet freed.
void moraine_dump_file_column_stats_free(struct MoraineFileColumnStatsRow *items, size_t len);

// Dumps every `ducklake_tag` row into `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_tags(struct MoraineCatalogHandle *handle,
                          struct MoraineTagRow **out_items,
                          size_t *out_len,
                          MoraineInterruptProbe probe,
                          void *probe_ctx,
                          struct MoraineError *err);

// Frees the array returned by [`moraine_dump_tags`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_tags`] call
// wrote, not yet freed.
void moraine_dump_tags_free(struct MoraineTagRow *items, size_t len);

// Dumps every `ducklake_column_tag` row into `*out_items`/`*out_len`.
//
// # Safety
//
// The shared dump-entry contract (`dump_rows`): a live `handle` from
// [`moraine_attach`](crate::abi::moraine_attach), valid writable
// `out_items`/`out_len`, a `probe` callable with `probe_ctx` from any
// thread, and a null-or-writable `err`, all for the duration of the
// call.
int32_t moraine_dump_column_tags(struct MoraineCatalogHandle *handle,
                                 struct MoraineColumnTagRow **out_items,
                                 size_t *out_len,
                                 MoraineInterruptProbe probe,
                                 void *probe_ctx,
                                 struct MoraineError *err);

// Frees the array returned by [`moraine_dump_column_tags`].
//
// # Safety
//
// `items`/`len` must be exactly the pair a matching [`moraine_dump_column_tags`] call
// wrote, not yet freed.
void moraine_dump_column_tags_free(struct MoraineColumnTagRow *items, size_t len);

// Materializes `table_id`'s inlined rows and selects the `scan_kind`
// variant (`0` = `SCAN_TABLE`, `1` = `SCAN_INSERTIONS`, `2` =
// `SCAN_DELETIONS`, `3` = `SCAN_FOR_FLUSH`) at `snapshot`, windowed from
// `start` for the incremental variants (ignored by `SCAN_TABLE`/
// `SCAN_FOR_FLUSH`).
//
// Cancellable: races the core read against `probe` (polled immediately,
// then ~100 ms; a null `probe` disables polling). If a cancellation
// wins, returns [`codes::INTERRUPTED`] and the out-params are left
// unwritten.
//
// # Safety
//
// `handle` must be a pointer previously returned by
// [`moraine_attach`](crate::abi::moraine_attach) and not yet detached.
// `out_items`/`out_len` must be valid, writable pointers. `probe`, if
// non-null, must be safe to call with `probe_ctx` from any thread.
// `err`, if non-null, must be a valid, writable [`MoraineError`]. All
// for the duration of this call.
int32_t moraine_inline_scan(struct MoraineCatalogHandle *handle,
                            uint64_t table_id,
                            int32_t scan_kind,
                            uint64_t snapshot,
                            uint64_t start,
                            struct MoraineInlineRow **out_items,
                            size_t *out_len,
                            struct MoraineInlineChunk **out_chunks,
                            size_t *out_chunks_len,
                            MoraineInterruptProbe probe,
                            void *probe_ctx,
                            struct MoraineError *err);

// Frees the row and chunk arrays returned by [`moraine_inline_scan`].
//
// # Safety
//
// `items`/`len` and `chunks`/`chunks_len` must be exactly the pointers
// and lengths written by one matching [`moraine_inline_scan`] call, not
// yet freed.
void moraine_inline_scan_free(struct MoraineInlineRow *items,
                              size_t len,
                              struct MoraineInlineChunk *chunks,
                              size_t chunks_len);

// Dumps every `(schema_version, arrow_schema)` recorded for `table_id`.
//
// # Safety
//
// Same pointer contract as [`moraine_inline_scan`].
int32_t moraine_inline_schemas(struct MoraineCatalogHandle *handle,
                               uint64_t table_id,
                               struct MoraineInlineSchemaRow **out_items,
                               size_t *out_len,
                               MoraineInterruptProbe probe,
                               void *probe_ctx,
                               struct MoraineError *err);

// Frees an array returned by [`moraine_inline_schemas`].
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_inline_schemas`] call, not yet freed.
void moraine_inline_schemas_free(struct MoraineInlineSchemaRow *items, size_t len);

// Dumps every `(table_id, schema_version)` with a recorded inline
// schema, across every table — feeds the `ducklake_inlined_data_tables`
// projection.
//
// # Safety
//
// Same pointer contract as [`moraine_inline_scan`].
int32_t moraine_inline_registered_tables(struct MoraineCatalogHandle *handle,
                                         struct MoraineInlineTableRow **out_items,
                                         size_t *out_len,
                                         MoraineInterruptProbe probe,
                                         void *probe_ctx,
                                         struct MoraineError *err);

// Frees an array returned by [`moraine_inline_registered_tables`]. No
// owned buffers inside — releases only the backing allocation.
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_inline_registered_tables`] call, not yet freed.
void moraine_inline_registered_tables_free(struct MoraineInlineTableRow *items, size_t len);

// Reports whether `table_id` has at least one recorded `inline/file_delete`
// record, via `*out_exists`. The shim's catalog lookup for
// `ducklake_inlined_delete_<table_id>` uses this to decide whether the
// table exists at all, so a probe against a table that never had one must
// surface a bind-time catalog error.
//
// # Safety
//
// Same pointer contract as [`moraine_inline_scan`], with `out_exists` in
// place of `out_items`/`out_len`.
int32_t moraine_inline_file_delete_table_exists(struct MoraineCatalogHandle *handle,
                                                uint64_t table_id,
                                                bool *out_exists,
                                                MoraineInterruptProbe probe,
                                                void *probe_ctx,
                                                struct MoraineError *err);

// Dumps every `inline/file_delete` record for `table_id` in
// `(file_id, row_id)` order — the rows behind the
// `ducklake_inlined_delete_<t>` projection.
//
// # Safety
//
// Same pointer contract as [`moraine_inline_scan`].
int32_t moraine_inline_file_deletes(struct MoraineCatalogHandle *handle,
                                    uint64_t table_id,
                                    struct MoraineInlineFileDeleteRow **out_items,
                                    size_t *out_len,
                                    MoraineInterruptProbe probe,
                                    void *probe_ctx,
                                    struct MoraineError *err);

// Frees an array returned by [`moraine_inline_file_deletes`]. No owned
// buffers inside — releases only the backing allocation.
//
// # Safety
//
// `items`/`len` must be exactly the pointer and length written by a
// matching [`moraine_inline_file_deletes`] call, not yet freed.
void moraine_inline_file_deletes_free(struct MoraineInlineFileDeleteRow *items, size_t len);

// Opens a staged-row transaction at the current head and writes the
// resulting handle to `*out`.
//
// Cancellable: races the head read against `probe` (polled
// immediately, then ~100 ms; a null `probe` disables polling). If a
// cancellation wins, returns [`codes::INTERRUPTED`], `*out` is left
// unwritten, and nothing is staged.
//
// # Safety
//
// `handle` must be a pointer previously returned by
// [`moraine_attach`](crate::abi::moraine_attach) and not yet detached,
// and must outlive every operation on the returned transaction handle
// (through [`moraine_tx_commit`] or [`moraine_tx_rollback`]). `out`
// must be a valid, writable `*mut *mut MoraineTxHandle`. `probe`, if
// non-null, must be safe to call with `probe_ctx` from any thread.
// `err`, if non-null, must be a valid, writable [`MoraineError`]. All
// for the duration of this call.
int32_t moraine_tx_begin(struct MoraineCatalogHandle *handle,
                         struct MoraineTxHandle **out,
                         MoraineInterruptProbe probe,
                         void *probe_ctx,
                         struct MoraineError *err);

// Accumulates one staged row mutation. Nothing touches the store until
// [`moraine_tx_commit`]. `table_kind` is [`TableKind`]'s discriminant
// order (`0` = `Snapshot`, `1` = `SnapshotChanges`, `2` = `Schema`, `3` =
// `Table`, `4` = `View`, `5` = `Column`, `6` = `DataFile`, `7` =
// `DeleteFile`, `8` = `TableStats`, `9` = `TableColumnStats`, `10` =
// `FileColumnStats`, `11` = `SchemaVersions`, `12` = `PartitionInfo`,
// `13` = `PartitionColumn`, `14` = `FilePartitionValue`, `15` =
// `SortInfo`, `16` = `SortExpression`, `17` = `Tag`, `18` =
// `ColumnTag`, `19` = `FilesScheduledForDeletion`); `operation_kind` is
// `0` = insert, `1` = delete, `2` = update-sets-`end_snapshot`, `3` =
// update-sets-`begin_snapshot`. `cells` are positional
// in the column order the shim declares for `table_kind`'s table (a delete
// or update-set-end row carries only the key columns, per [`RowOperation`]'s
// variants).
//
// # Safety
//
// `tx` must be a pointer previously returned by [`moraine_tx_begin`]
// and not yet committed or rolled back. `cells`, if `cells_len` is
// nonzero, must point to `cells_len` valid [`MoraineCell`]s (every
// non-null `str_value` inside a valid NUL-terminated UTF-8 C string).
// `err`, if non-null, must be a valid, writable [`MoraineError`]. All
// for the duration of this call.
int32_t moraine_tx_stage(struct MoraineTxHandle *tx,
                         int32_t table_kind,
                         int32_t operation_kind,
                         const struct MoraineCell *cells,
                         size_t cells_len,
                         struct MoraineError *err);

// Dumps every `ducklake_snapshot` row **as this transaction sees it**:
// committed rows at the transaction's read point minus the snapshot
// deletes staged so far. The expiry cascade's own `NOT EXISTS`
// subqueries re-read `ducklake_snapshot` after staging deletes and must
// observe them — a committed-state dump would silently under-reclaim.
// Freed with `moraine_dump_snapshots_free`.
//
// # Safety
//
// `tx` must be a pointer previously returned by [`moraine_tx_begin`]
// and not yet committed or rolled back; its catalog must still be
// attached. `out_items`/`out_len` must be valid, writable pointers.
// `err`, if non-null, must be a valid, writable [`MoraineError`]. All
// for the duration of this call.
int32_t moraine_tx_dump_snapshots(struct MoraineTxHandle *tx,
                                  struct MoraineSnapshotRow **out_items,
                                  size_t *out_len,
                                  struct MoraineError *err);

// Translates every staged row and lands them in one atomic batch,
// consuming `tx`. On success, writes the new snapshot id to
// `*out_snapshot_id`.
//
// A lost race against a concurrent commit is never retried internally: it
// returns [`codes::COMMIT_CONFLICT`] with the literal substring `conflict`
// in the message, and the loser leaves the store unchanged. `tx` is freed
// either way; it must not be passed to [`moraine_tx_rollback`]
// afterward.
//
// # Safety
//
// `tx` must be a pointer previously returned by [`moraine_tx_begin`]
// and not yet committed or rolled back. `out_snapshot_id` must be a
// valid, writable `*mut u64`. `err`, if non-null, must be a valid,
// writable [`MoraineError`]. All for the duration of this call. The
// catalog handle `tx` was opened on ([`moraine_tx_begin`]'s contract)
// must still be attached.
int32_t moraine_tx_commit(struct MoraineTxHandle *tx,
                          uint64_t *out_snapshot_id,
                          struct MoraineError *err);

// Discards every staged row without writing anything, consuming `tx`.
// Best-effort: has no error channel. A null `tx` is a no-op.
//
// # Safety
//
// `tx`, if non-null, must be a pointer previously returned by
// [`moraine_tx_begin`] and not yet committed or rolled back.
void moraine_tx_rollback(struct MoraineTxHandle *tx);

// Stages `inline/schema`: the Arrow IPC schema for one `(table_id,
// schema_version)`, written once at inline-table creation.
//
// # Safety
//
// `tx` must be a pointer previously returned by [`moraine_tx_begin`]
// and not yet committed or rolled back. `arrow_schema`, if
// `arrow_schema_len` is nonzero, must point to `arrow_schema_len` valid
// bytes. `err`, if non-null, must be a valid, writable [`MoraineError`].
// All for the duration of this call.
int32_t moraine_tx_stage_inline_schema(struct MoraineTxHandle *tx,
                                       uint64_t table_id,
                                       uint64_t schema_version,
                                       const uint8_t *arrow_schema,
                                       size_t arrow_schema_len,
                                       struct MoraineError *err);

// Stages `inline/insert`: one Arrow record-batch chunk of inlined rows.
//
// # Safety
//
// Same `tx` contract as [`moraine_tx_stage_inline_schema`].
// `arrow_body`, if `arrow_body_len` is nonzero, must point to
// `arrow_body_len` valid bytes. `err`, if non-null, must be a valid,
// writable [`MoraineError`]. All for the duration of this call.
int32_t moraine_tx_stage_inline_insert(struct MoraineTxHandle *tx,
                                       uint64_t table_id,
                                       uint64_t schema_version,
                                       uint64_t begin_snapshot,
                                       uint64_t row_id_start,
                                       uint64_t row_count,
                                       const uint8_t *arrow_body,
                                       size_t arrow_body_len,
                                       struct MoraineError *err);

// Stages `inline/inline_delete`: tombstones one inlined-insert row.
//
// # Safety
//
// `tx` must be a pointer previously returned by [`moraine_tx_begin`]
// and not yet committed or rolled back. `err`, if non-null, must be a
// valid, writable [`MoraineError`]. Both for the duration of this call.
int32_t moraine_tx_stage_inline_inline_delete(struct MoraineTxHandle *tx,
                                              uint64_t table_id,
                                              uint64_t row_id,
                                              uint64_t end_snapshot,
                                              struct MoraineError *err);

// Stages `inline/file_delete`: an inlined delete against a Parquet-file row.
//
// # Safety
//
// Same contract as [`moraine_tx_stage_inline_inline_delete`].
int32_t moraine_tx_stage_inline_file_delete(struct MoraineTxHandle *tx,
                                            uint64_t table_id,
                                            uint64_t data_file_id,
                                            uint64_t row_id,
                                            uint64_t begin_snapshot,
                                            struct MoraineError *err);

// Stages a flush-delete: removes every `inline/insert` chunk begun at or
// before `flush_snapshot` for `(table_id, schema_version)`, plus the
// `inline/inline_delete` tombstones those chunks' rows consumed.
//
// # Safety
//
// Same contract as [`moraine_tx_stage_inline_inline_delete`].
int32_t moraine_tx_stage_inline_flush_delete(struct MoraineTxHandle *tx,
                                             uint64_t table_id,
                                             uint64_t schema_version,
                                             uint64_t flush_snapshot,
                                             struct MoraineError *err);

// Stages a table drop: removes every `inline/*` record for `table_id`.
//
// # Safety
//
// `tx` must be a pointer previously returned by [`moraine_tx_begin`]
// and not yet committed or rolled back. `err`, if non-null, must be a
// valid, writable [`MoraineError`]. Both for the duration of this call.
int32_t moraine_tx_stage_inline_drop(struct MoraineTxHandle *tx,
                                     uint64_t table_id,
                                     struct MoraineError *err);

// Stages a schema-version-scoped deregistration: removes only the
// `inline/schema` record for `(table_id, schema_version)`, leaving any
// other schema version's `inline/*` records untouched (unlike
// [`moraine_tx_stage_inline_drop`], which is table-wide).
//
// # Safety
//
// Same contract as [`moraine_tx_stage_inline_drop`].
int32_t moraine_tx_stage_inline_schema_drop(struct MoraineTxHandle *tx,
                                            uint64_t table_id,
                                            uint64_t schema_version,
                                            struct MoraineError *err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
